# ---- Site basics ----
title: "Kara Combs"
subtitle: "Engineer • Researcher"
description: "Academic homepage: research, publications, teaching, contact."
url: "https://kcombs15.github.io"
baseurl: ""   # keep empty for user/organization site repos
repository: "kcombs15/kcombs15.github.io"

# ---- Theme ----
remote_theme: "mmistakes/minimal-mistakes"

# Performance/cache for GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-include-cache

# Build options
markdown: kramdown
permalink: /:categories/:title/
paginate: 5
paginate_path: "/blog/page:num/"

# Author block (shows on about page & post headers)
author:
  name: "Kara Combs"
  avatar: "/assets/img/Combs_Digital_Portrait.png" # add later if you like
  bio: "Engineer and PhD researcher in OR/AI. Interests: analogical reasoning, knowledge graphs, causal inference."
  location: "Dayton, OH"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:YOUR_EMAIL@domain.com"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"    # academic icons are supported if CSS is included; otherwise keep std icons
      url: "https://scholar.google.com/citations?user=TOV6TicAAAAJ"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/kcombs15"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/karacombs33/"

# Minimal Mistakes settings
theme_settings:
  # optional; extra toggles if you want
  # show_date: false
  # reading_time: true
  # toc: true
  # toc_sticky: true
  # search: true

# Navigation (pulled from _data/navigation_header.yml)
collections:
  pages:
    output: true
    permalink: /:path/

# Defaults: apply layout to pages and posts
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true

# Exclude things from the build if you add them later
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
