---
title: "Education & Experience"
page-layout: article
---

## Education
- Ph.D. Operations Research, *Air Force Institute of Technology*, Jan. 2023 – present
- M.S. Industrial and Human Factors Engineering, *Wright State University*, Aug. 2019 - Dec. 2021
- B.S. Industrial and Systems Engineering, *Wright State University*, Aug. 2017 - May 2021

## Experience
- Computer Engineer, *Air Force Research Laboratory (Sensors Directorate)*, Jan. 2025 - present
- Associate Computer Engineer, *Air Force Research Laboratory (Sensors Directorate)*, Feb. 2023 - Jan. 2025
- Research Engineer, *Applied Research Solutions*, Apr. 2022 - Feb. 2023
- Graduate Research Assistant, *Wright State University*, May 2021 - Dec. 2021
- Research Engineer Intern, *Applied Research Solutions*, May 2020 - Mar. 2022

## Grants & Funding
- Dynamic Analogical Inference for Adaptive Data Representation and Fusion, *Air Force Research Laboratory Sensors Directorate*
  - Period of Performance: Feb. 2025 - Jul. 2026
  - Amount: $75,000
  - Team: K. Combs (PI)
- Analogical Learning for Aerial Sensing Autonomy, *Air Force Research Laboratory Sensors Directorate*
  - Period of Performance: Feb. - Nov. 2024
  - Amount: $75,000
  - Team: K. Combs (PI)
- TechFest Dayton: Large-scale K-12 STEM Outreach, *INFORMS 2024 Ambassadors Program*
  - Period of Performance: Jan. - Dec. 2024
  - Amount: $500
  - Team: K. Combs (PI), N. Gaw (Co-PI), & T. Bihl (Co-PI)

## Certifications & Licenses
- [AFRL Introduction to Intellectural Property Certification](https://badgr.com/public/assertions/JIRBkpQdSGGd578s8TKqeg?identity__email=kara.combs.1@us.af.mil), *AFRL & University of Dayton School of Law*
- [Fundamentals of Systems Acquisition Management (ACQ 1010)](https://www.credly.com/badges/be101b3e-630a-4605-ad5e-036a90e1419a/public_url), *Defense Acquisition University*
- [Ohio Engineering Intern License](https://elicense.ohio.gov/oh_verifylicensedetails?pid=a0Rt00000045Jb9EAE), *Ohio State Board of Registration for Professional Engineers and Surveyors*
- [Business Analytics Certificate](https://www.credly.com/badges/966d80ed-90fc-476e-b5a2-40c0d6f82aac), *SAS & Wright State University*

## Professional Memberships
- American Society for Engineering Education (ASEE)
  - Student Member, 2025 - Present
- Association for the Advancement of Artificial Intelligence (AAAI)
  - Student Member, 2025 - Present
<!-- - Assocation for Computing Machinery (ACM)
  - Professional Member, 2024 - 2025 -->
- Institute for Operations Research and the Management Sciences (INFORMS)
  - Profesional Member, 2022 - Present
  - Student Member, 2021 - 2022
<!-- - Institute for Electrical and Electronics Engineers (IEEE)
  - Student Member, 2024 - 2025 -->
<!-- - Institute of Industrial and Systems Engineers (IISE)
  - Professional Member, 2021 - 2023
  - Student Member, 2017 - 2021 -->
- Military Operations Research (MORS)
  - Student Member, 2025 - Present
- Order of the Engineer (ethics pledge)
  - Inductee, 2021
- Society of Women Engineers (SWE)
  - Student Member, 2023 - Present
  - Professional Member, 2022 - 2023
- Tau Beta Pi (engineering honor society)
  - Initiate, 2019
- Women in Defense (WID)
  - Member, 2025 - Present