name: Publish Quarto site

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Quarto
      - uses: quarto-dev/quarto-actions/setup@v2

      # If you run Python code cells in .qmd, keep these 2 steps.
      # If not, you may delete them.
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install jupyter  # or: pip install -r requirements.txt

      # Build the site to _site/
      - name: Render
        run: quarto render

      # Upload _site/ as the Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
